using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Voting.UI;

[GenerateTypedNameReferences]
public sealed partial class VoteContainer : UIWidget
{
    public VoteContainer()
    {
        RobustXamlLoader.Load(this);
    }
}