using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Voting.UI;

[GenerateTypedNameReferences]
public sealed partial class VotePopup : Control
{
    public VotePopup()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetSpace;
    }
}